### PR TITLE
making request builder immutable

### LINKED ISSUE #3: Prefer constructor injection, drop lazy initialization
I think I already mentioned this somewhere: setter injection and lazy initialization is not really a good idea with the discovery IMO. I think it's better to fail early and know as soon as possible if something is missing. Also, setters doesn't really make sense in most of the cases, as the request builder for example is not used outside of the API context.

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #3. Avoid lazy loading.

### CODE REVIEW

File: src/RequestBuilder.php [hunk 1]
```diff
@@ -73,46 +85,14 @@ public function create($method, $uri, array $headers = [], $body = null): Reques
      */
     private function getRequestFactory(): RequestFactory
```
Comment (sagikazarmark) [inline src/RequestBuilder.php]: Do we need these, if lazy initialization is removed?

Comment (Nyholm) [reply src/RequestBuilder.php]: Nope =)

Thanks

**Comment by Nyholm** [comment]
Thank you for merging
